### ISSUE TITLE
Licensing question 

### ISSUE THREAD

**Issue by btopro** [admwx7/am-image-cropper#9]
Would you consider licensing as apache 2.0? I think it could increase potential adoption in larger projects as this would always be included in bigger things. With gplv3 it's kind of hard to include it in anything that isn't also gplv3.

**Comment by admwx7** [comment]
I'll switch it, didn't realize GPL3 forced all works that touch it to be GPL.  Was looking for something akin to creative commons 4, I want all derivative work to be open source, if you use it as-is I don't really care much what you do with it.
